#!/usr/bin/env bash
# dependencies: php git bash

# Lint
composer run-script lint

# Enforce TCR (Test && Commit || Revert)
php artisan test

if [ $? -eq 0 ]; then
    # Commit changes
    exit 0
else
    # Reset changes but keep tests
    git diff --name-only | grep -v 'tests' | xargs git restore --source=HEAD --staged --worktree
    exit 1
fi
