#!/usr/bin/env bash
# description: Git hook to enforce TCR (Test && Commit || Revert)
# dependencies: php git bash

# Run tests
php artisan test

if [ $? -eq 0 ]; then
    # Commit changes
    exit 0
else
    # Reset changes but keep tests
    git restore --source=HEAD --staged --worktree -- $(git diff --name-only | grep -v 'tests')
    exit 1
fi
